apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-consumption-prediction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-consumption-prediction
  template:
    metadata:
      labels:
        app: energy-consumption-prediction
    spec:
      containers:
      - name: energy-consumption-prediction
        image: oaslananka/energy-consumption-prediction:latest
        ports:
        - containerPort: 80
