# This YAML file defines a Kubernetes Deployment for the energy-consumption-prediction application.
# It specifies the desired state of the deployment, including the number of replicas, selector labels, and container configuration.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: energy-consumption-prediction
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energy-consumption-prediction
  template:
    metadata:
      labels:
        app: energy-consumption-prediction
    spec:
      containers:
      - name: energy-consumption-prediction
        image: your-dockerhub-username/energy-consumption-prediction:latest
        ports:
        - containerPort: 80
