apiVersion: v1
kind: Service
metadata:
  name: energy-consumption-prediction
spec:
  selector:
    app: energy-consumption-prediction
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
  type: NodePort
